### ISSUE TITLE
Inverter Throwing Fault code 18 when AC Charge Priority or set time is in the Code.

### ISSUE THREAD

**Issue by PeitzGreene** [adamksmith/ESPHome-Projects#1]
So currently running into an issue when AC Charge Priority or set time are in the esphome config it has the inverter trip a fault code 18.

It will switch over to the grid then back the batteries and repeat. Im guessing it is a issue with the esp sending something the Inverter.

All that was change in my code is the gpio pins where updated and added a pin for flow control to work with the MAX485 (the style with the green header on top for the bus)

```
uart:
  - id: uart_modbus_inverter_1
    rx_pin: GPIO16
    tx_pin: GPIO17
    baud_rate: 19200
    stop_bits: 1

modbus:
  - uart_id: uart_modbus_inverter_1
    id: modbus_inverter_1
    flow_control_pin: GPIO4

modbus_controller:
  - address: 1
    update_interval: 5s
    modbus_id: modbus_inverter_1
    id: inverter_1
```

I had it up and running for about 10 hours before it started doing this.

I have 2 v2 lifepower batteries and 3 v1, I did recently update the firmware on the v2 because was getting wrong SOC from the v1s.

But after doing that I am still having the same issue.

Still troubleshooting and will report back

Also working on a way if possible to be able to report back the SOC and other Battery info of each battery and a simple wiring diagram.

Wanted to make an issue to see if anyone else if running into the same issue.
